/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.anywide.shop.activity;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int black=0x7f040003;
        public static final int black_light=0x7f040009;
        public static final int common_bg_pressed=0x7f040002;
        public static final int common_line=0x7f040000;
        public static final int dark_gray=0x7f04000a;
        public static final int gray=0x7f04000b;
        public static final int impt=0x7f040008;
        public static final int login_background=0x7f04000c;
        public static final int main_red=0x7f04000f;
        public static final int main_top_bg_active=0x7f040006;
        public static final int main_top_bg_gray=0x7f040005;
        public static final int main_top_color_gray=0x7f040007;
        public static final int tab=0x7f04000d;
        public static final int tab_selected=0x7f04000e;
        public static final int transparent=0x7f040001;
        public static final int white=0x7f040004;
    }
    public static final class dimen {
        public static final int action_bar_button_min_width=0x7f050001;
        public static final int action_bar_height=0x7f050000;
        public static final int index_tab_height=0x7f050004;
        public static final int index_tab_icon_margin_top=0x7f050002;
        public static final int max_radius=0x7f050003;
    }
    public static final class drawable {
        public static final int btn_gray=0x7f020000;
        public static final int btn_main=0x7f020001;
        public static final int color_tab=0x7f020002;
        public static final int common_background=0x7f020003;
        public static final int dot=0x7f020004;
        public static final int ic_back=0x7f020005;
        public static final int ic_cart_black=0x7f020006;
        public static final int ic_home=0x7f020007;
        public static final int ic_home_selected=0x7f020008;
        public static final int ic_launcher=0x7f020009;
        public static final int ic_login_pwd=0x7f02000a;
        public static final int ic_login_user=0x7f02000b;
        public static final int ic_refresh_gray=0x7f02000c;
        public static final int ic_user=0x7f02000d;
        public static final int ic_user_selected=0x7f02000e;
        public static final int ic_win=0x7f02000f;
        public static final int ic_win_selected=0x7f020010;
        public static final int main_top_bg=0x7f020011;
        public static final int tab_border=0x7f020012;
        public static final int tab_home=0x7f020013;
        public static final int tab_result=0x7f020014;
        public static final int tab_user=0x7f020015;
        public static final int top_gray_border=0x7f020016;
    }
    public static final class id {
        public static final int action_edit=0x7f08001f;
        public static final int animation_wrapper=0x7f08000b;
        public static final int email=0x7f080004;
        public static final int email_icon=0x7f080003;
        public static final int email_wrapper=0x7f080002;
        public static final int login=0x7f080009;
        public static final int login_forget=0x7f080008;
        public static final int login_main=0x7f080000;
        public static final int login_normal=0x7f080001;
        public static final int login_reg=0x7f08000a;
        public static final int pass_wrapper=0x7f080006;
        public static final int password=0x7f080005;
        public static final int pwd_icon=0x7f080007;
        public static final int register=0x7f080019;
        public static final int tab=0x7f08000d;
        public static final int tab_dot4=0x7f080018;
        public static final int tab_icon0=0x7f08000f;
        public static final int tab_icon1=0x7f080012;
        public static final int tab_icon4=0x7f080016;
        public static final int tab_icon_wrapper4=0x7f080015;
        public static final int tab_label0=0x7f080010;
        public static final int tab_label1=0x7f080013;
        public static final int tab_label4=0x7f080017;
        public static final int tab_wrapper0=0x7f08000e;
        public static final int tab_wrapper1=0x7f080011;
        public static final int tab_wrapper4=0x7f080014;
        public static final int toolbar=0x7f08001a;
        public static final int top_back=0x7f08001b;
        public static final int top_cart=0x7f08001e;
        public static final int top_refresh=0x7f08001d;
        public static final int top_text_center=0x7f08001c;
        public static final int view_pager=0x7f08000c;
    }
    public static final class layout {
        public static final int activity_baby=0x7f030000;
        public static final int activity_goods=0x7f030001;
        public static final int activity_login=0x7f030002;
        public static final int activity_main=0x7f030003;
        public static final int activity_register1=0x7f030004;
        public static final int include_top_adjust_gray=0x7f030005;
    }
    public static final class string {
        public static final int action_edit=0x7f06000b;
        public static final int app_name=0x7f060000;
        /**  注册 
         */
        public static final int btn_register=0x7f06000e;
        /**  登录 
         */
        public static final int desc_common_image=0x7f060005;
        public static final int error_login_phone=0x7f06000c;
        public static final int error_login_pwd=0x7f06000d;
        public static final int forgot_password=0x7f060008;
        public static final int free_mail=0x7f060006;
        /**  共同 
         */
        public static final int global_tip_loading=0x7f060003;
        public static final int global_title_me=0x7f060004;
        public static final int hello_world=0x7f060001;
        public static final int login=0x7f060009;
        public static final int password=0x7f060007;
        public static final int register=0x7f06000a;
        public static final int tab_goods=0x7f060014;
        /**  主页面 
         */
        public static final int tab_home=0x7f060012;
        public static final int tab_user=0x7f060013;
        public static final int title_activity_baby=0x7f060015;
        public static final int title_activity_goods=0x7f060016;
        public static final int title_activity_login=0x7f060002;
        public static final int txt_register1=0x7f06000f;
        public static final int txt_register2=0x7f060010;
        public static final int txt_register3=0x7f060011;
    }
    public static final class style {
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        

        Base application theme for API 11+. This theme completely replaces
        AppBaseTheme from res/values/styles.xml on API 11+ devices.
    
 API 11 theme customizations can go here. 

        Base application theme for API 14+. This theme completely replaces
        AppBaseTheme from BOTH res/values/styles.xml and
        res/values-v11/styles.xml on API 14+ devices.
    
 API 14 theme customizations can go here. 
         */
        public static final int AppBaseTheme=0x7f070000;
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f070001;
        public static final int Dot=0x7f070005;
        public static final int EidtCont=0x7f070003;
        public static final int LoginEidtCont=0x7f070004;
        public static final int ShipAddressEidtCont=0x7f070002;
    }
}
